Eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
    path('users/', include('users.urls', namespace='users')),  # Включаем URL-маршруты из приложения 'users'
    path("__debug__/", include("debug_toolbar.urls")),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('edit/<int:product_id>/', views.cart_edit, name='cart_edit'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    ]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('list/', views.my_orders_list, name='my_orders_list'),
]

shop/urls.py
from . import views
from django.urls import path, include, re_path

app_name = 'shop'

urlpatterns = [

    path('', views.show_index, name='index'),

    re_path(r'^catalog', views.show_categories, name='show_categories'),
    re_path(r'^catalog/(?P<url_path>.+)/$', views.show_categories, name='show_categories'),
    # path('category/<slug:category_slug>/', views.category_detail, name='category_detail'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('brand/<int:brand_id>/', views.show_brand_catalog, name='show_brand_catalog'),
    path('search/', views.product_search, name='product_search'),
    path('contacts/', views.contacts, name='contacts'),

    path("__debug__/", include("debug_toolbar.urls")),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from shop.models import Size, Color


# ограничиваем выбор кол-ва единиц товара до 20
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    # Добавляем поля для выбора размера и цвета
    size = forms.ModelChoiceField(queryset=Size.objects.all(), empty_label=None)
    color = forms.ModelChoiceField(queryset=Color.objects.all(), empty_label=None)
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)

    # override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

class CartEditProductForm(forms.Form):
    # выбор кол-ва товара от 1 до 20
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product, Product_Images
from .cart import Cart
from .forms import CartAddProductForm, CartEditProductForm
from shop.utils import generate_breadcrumbs

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    # print('hello')
    product = get_object_or_404(Product, id=product_id)
    images = Product_Images.objects.filter(product_id=product.id)

    form = CartAddProductForm(request.POST)

    # print(form.__dict__)
    # print(form.is_valid())
    if form.is_valid():
        cd = form.cleaned_data
        # Получите данные о размере и цвете
        size = form.cleaned_data['size']
        color = form.cleaned_data['color']
        # print(f"quantity= {cd['quantity']}, override_quantity= {cd['override']}")
        cart.add(product=product, size=size, color=color,
                 images=images, quantity=cd['quantity'])

    return redirect('cart:cart_detail')


@require_POST
def cart_edit(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)

    form = CartEditProductForm(request.POST)

    # print(form.__dict__)
    # print(form.is_valid())
    if form.is_valid():
        cd = form.cleaned_data
        print(f"quantity= {cd['quantity']}")
        cart.edit(product=product, quantity=cd['quantity'])

    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)

    # redirect чтобы заново не отправлять POST данные, если снова обновить страницу
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)

    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],
                                                                   'override': True})

    title = 'Корзина'
    # Получение текущего пути
    current_path = request.path_info
    # Генерация breadcrumbs
    breadcrumbs = generate_breadcrumbs(current_path, title)

    return render(request, 'cart/detail.html', {'cart': cart,
                                                'breadcrumbs': breadcrumbs,
                                                'title': title})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block content %}
{% load pluralize_ru %}
    <div class="breadcrumb-box">
                <div class="container">
                    <div class="menu_box">
                        <ol class="breadcrumb">
                            {% for crumb in breadcrumbs %}
                                <li><a href="{{ crumb.url }}">{{ crumb.name }}</a></li>
                            {% endfor %}
                        </ol>
                    </div>
                </div>
            </div>
{#<div class="men">#}
    <div class="container">
	<div class="check">
		<div class="col-md-9 cart-items">
			 <h4 class="title">Ваша корзина покупок</h4>
				<script>$(document).ready(function(c) {
					$('.close1').on('click', function(c){
						$('.cart-header').fadeOut('slow', function(c){
							$('.cart-header').remove();
						});
						});
					});
			   </script>

            {% for item in cart %}
                {% with product=item.product %}


                <div class="cart-header">
                    <div class="close1">
                        <form action="{% url "cart:cart_remove" product.id %}" method="post">
                            <button type="submit" class="image-button"></button>
                            {% csrf_token %}
                        </form>
                    </div>
				 <div class="cart-sec simpleCart_shelfItem">
                     <div class="cart-item">
                         <a href="{% url 'shop:product_detail' product.id %}">
                             <img src="{% if item.images %}{{ item.images_url }}{{ item.images.0.img_thumb }}
      {% else %}{% static "images/img69.jpg" %}{% endif %}"></a>

                     </div>
					   <div class="cart-item-info">
						<h3><a href="{% url 'shop:product_detail' product.id %}">{{ product.name }} </a>
                            <span><a href="{% url 'shop:show_brand_catalog' product.brand_id %}">{{ product.brand_name }}</a></span></h3>
						<ul class="qty">
							<li><p>{{ item.size }}</p></li>
							<li><p>{{ item.color }}</p></li>
                            <li><p>
                                <form action="{% url "cart:cart_edit" product.id %}" method="post">
                                    {{ item.update_quantity_form.quantity }}
                                    <input type="submit" value="Изменить">
                                    {% csrf_token %}
                                </form></p></li>
                            <li><p>{{ item.price }}</p></li>
                            <li><p>{{ item.total_price }}</p></li>
						</ul>
{#						<div class="delivery">#}
{#							 <p>Service Charges : Rs.100.00</p>#}
{#							 <span>Delivered in 2-3 business days</span>#}
{#							 <div class="clearfix"></div>#}
{#				        </div>#}
					   </div>
					   <div class="clearfix"></div>

				  </div>
			 </div>

{% endwith %}
{% endfor %}

        </div>
		 <div class="col-md-3 cart-total">
			 <a class="continue" href="{% url "shop:index" %}">Добавить товары</a>
			 <div class="price-details">
{#				 <h3>Общее количество</h3>#}
				 <span>Количество:</span>

                 {% with total_items=cart|length %}
                     {% if total_items > 0 %}

                         <span>{{ total_items }} {{ total_items|pluralize_ru:"товар,товара,товаров" }}</span>
                     {% else %}
                         <span class="total1">Ваша корзина пуста</span>
                     {% endif %}
                 {% endwith %}
                <div class="clearfix"></div>
			 </div>
             <ul class="total_price">
                 <li class="last_price"><h4>Итого:</h4></li>
                 <li class="last_price"><span>{{ cart.get_total_price }} ₽</span></li>
             </ul>
             <div class="clearfix"></div>

             <a class="order" href="{% url "orders:order_create" %}">Оформить заказ</a>

{#			 <div class="total-item">#}
{#				 <h3>OPTIONS</h3>#}
{#				 <h4>COUPONS</h4>#}
{#				 <a class="cpns" href="#">Apply Coupons</a>#}
{#				 <p><a href="#">Log In</a> to use accounts - linked coupons</p>#}
{#			 </div>#}
			</div>
	 </div>
</div>
{#</div>#}










{#    <h1>Ваша корзина покупок</h1>#}
{#    <table class="cart">#}
{#        <thead>#}
{#        <tr>#}
{#            <th>Image&nbsp;</th>#}
{#            <th>Product </th>#}
{#            <th>Размер </th>#}
{#            <th>Цвет </th>#}
{#            <th>Quantity&nbsp;&nbsp;</th>#}
{#            <th>Remove&nbsp;&nbsp;</th>#}
{#            <th>Unit price&nbsp;&nbsp;</th>#}
{#            <th>Price</th>#}
{#        </tr>#}
{#        </thead>#}
{#        <tbody>#}
{##}
{#{% for item in cart %}#}
{#    {{ item }}#}
{#    <br>#}
{#    {% with product=item.product %}#}
{#        <tr>#}
{#            <td style="padding-top: 16px">#}
{#                <a href="{{ product.get_absolute_url }}">#}
{#<img src="{% if item.images %}{{ item.images_url }}{{ item.images.0.img_thumb }}#}
{#      {% else %}{% static "images/img69.jpg" %}#}
{#      {% endif %}">#}
{#                </a>#}
{#            </td>#}
{#            <td>{{ product.name }} {{ product.brand_name }}&nbsp;</td>#}
{#            <td>{{ item.size }}&nbsp;</td>#}
{#            <td>{{ item.color }}&nbsp;</td>#}
{#            <td>#}
{#                <form action="{% url "cart:cart_edit" product.id %}" method="post">#}
{#                    {{ item.update_quantity_form.quantity }}#}
{#                    <input type="submit" value="Изменить">#}
{#                    {% csrf_token %}#}
{#                </form>#}
{#            </td>#}
{#            <td>#}
{#                <form action="{% url "cart:cart_remove" product.id %}" method="post">#}
{#                    <input type="submit" value="Удалить">#}
{#                    {% csrf_token %}#}
{#                </form>#}
{#            </td>#}
{#            <td class="num">{{ item.price }} ₽</td>#}
{#            <td class="num">{{ item.total_price }} ₽</td>#}
{#        </tr>#}
{#    {% endwith %}#}
{#{% endfor %}#}
{#        <tr class="total">#}
{#            <td style="padding-top: 16px">Итого</td>#}
{#            <td colspan="4"></td>#}
{#            <td class="num">{{ cart.get_total_price }} ₽</td>#}
{#        </tr>#}
{#        </tbody>#}
{#    </table>#}
{#    <br>#}
{#    <p class="text-left">#}
{#        <a href="{% url "shop:index" %}" class="button-light">Продолжить покупки</a>#}
{#        <a href="{% url "orders:order_create" %}" class="button">Заказать товары</a>#}
{#    </p>#}
{% endblock %}