Eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('', include('shop.urls', namespace='shop')),
    path('users/', include('users.urls', namespace='users')),  # Включаем URL-маршруты из приложения 'users'
    path("__debug__/", include("debug_toolbar.urls")),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('edit/<int:product_id>/', views.cart_edit, name='cart_edit'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    ]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('list/', views.my_orders_list, name='my_orders_list'),
]

shop/urls.py
from . import views
from django.urls import path, include, re_path

app_name = 'shop'

urlpatterns = [

    path('', views.show_index, name='index'),

    re_path(r'^catalog', views.show_categories, name='show_categories'),
    re_path(r'^catalog/(?P<url_path>.+)/$', views.show_categories, name='show_categories'),
    # path('category/<slug:category_slug>/', views.category_detail, name='category_detail'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('brand/<int:brand_id>/', views.show_brand_catalog, name='show_brand_catalog'),
    path('search/', views.product_search, name='product_search'),
    path('contacts/', views.contacts, name='contacts'),

    path("__debug__/", include("debug_toolbar.urls")),
]

users/urls.py
from django.urls import path
from .views import register, profile, WishlistView
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'users'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', profile, name='profile'),
    path('wishlist/', WishlistView.as_view(), name='wishlist')
]

shop/forms.py
from django import forms

class SearchForm(forms.Form):
    search_query = forms.CharField(widget=forms.TextInput(attrs={'type': 'text'}))

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Prefetch
from .models import Category, Brand, Product, Color, Size, Product_Images
from Eshop.settings import BASE_DIR, MEDIA_ROOT, IMAGES_URL
from cart.forms import CartAddProductForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .utils import generate_breadcrumbs
from shop.forms import SearchForm
from django.db.models import Q

def get_category_and_parents(slug):
    # Метод get_family() используется в библиотеке MPTT
    category = get_object_or_404(Category, slug=slug)
    # parents_category = [{'id': '/', 'name': 'Главная'}] + list(category.get_family().values('id', 'name', 'slug'))
    parents_category = category.get_family().values_list('slug', flat=True)
    return parents_category

def get_category_and_descendants(slug):
    # Метод get_descendants() используется в библиотеке MPTT для получения всех потомков данной категории в дереве.
    # В MPTT, каждый узел дерева имеет левый и правый индексы, а получение потомков основано на этих индексах.
    category = get_object_or_404(Category, slug=slug)
    descendants_ids = [category.id] + list(category.get_descendants().values_list('id', flat=True))
    return category, descendants_ids


def show_categories(request):
    # Получение текущего пути
    current_path = request.path_info
    # Проверка, заканчивается ли путь слэшем, и добавление его, если необходимо
    if current_path[-1] != '/':
        current_path += '/'
    # Разделение пути на список компонентов
    path_info = current_path.split('/')
    # print(path_info)
    # Получение текущей категории и ее потомков на основе последнего компонента пути
    category, descendants_ids = get_category_and_descendants(path_info[-2])
    # print(descendants_ids)

    # Создание списка слагов из непустых компонентов пути
    slug_list = [x for x in path_info if x]
    breadcrumbs = []
    for slug in slug_list:
        # Для каждого слага в списке строится запрос категории по слагу, и результат добавляется в "хлебные крошки"
        breadcrumbs.append(Category.objects.filter(slug=slug))

    print(breadcrumbs)
    # Получение всех продуктов, относящихся к текущей категории и ее потомкам
    all_products = Product.objects.filter(category_id__in=descendants_ids).prefetch_related('images')

    # Применение сортировки
    # Получаем уникальные бренды для использования в выпадающем списке
    unique_brands = Product.objects.values_list('brand_name', flat=True).distinct()
    filtered_products = all_products  # Инициализация переменной перед использованием

    sort_param = request.GET.get('brand_name', 'default')

    if sort_param in unique_brands:
        selected_brand = request.GET.get('brand_name', None)

        if selected_brand:
            filtered_products = all_products.filter(brand_name=selected_brand)

    selected_gender = request.GET.get('gender', None)
    if selected_gender:
        filtered_products = all_products.filter(gender=selected_gender)

    sort_param = request.GET.get('sort', 'default')

    if sort_param == 'price_max':
        filtered_products = all_products.order_by('-price')
    elif sort_param == 'price_min':
        filtered_products = all_products.order_by('price')
    else:
        pass
    # Обработка значения 'default'

    # Применение пагинации
    paginator = Paginator(filtered_products, 6)  # Показываем кол-во товара на странице
    page = request.GET.get('page')

    try:
        filtered_products = paginator.page(page)
    except PageNotAnInteger:
        # Если page не является целым числом, отображаем первую страницу
        filtered_products = paginator.page(1)
    except EmptyPage:
        # Если страница выходит за пределы доступных страниц, отображаем последнюю страницу
        filtered_products = paginator.page(paginator.num_pages)

    last_value = [tree_queryset.last() for tree_queryset in breadcrumbs if tree_queryset.exists()]
    # print(last_value[-1])
    title = last_value[-1]

    return render(request, 'shop/category_detail.html', {'category': category,
                                                         'products': filtered_products,
                                                         'unique_brands': unique_brands,
                                                         'sort_param': sort_param,
                                                         'breadcrumbs': breadcrumbs,
                                                         'IMAGES_URL': IMAGES_URL,
                                                         'title': title
                                                         })


def show_index(request):
    categories = Category.objects.all()  # Получите все категории из базы данных
    all_products = Product.objects.all().prefetch_related('images')

    # Применение сортировки
    # Получаем уникальные бренды для использования в выпадающем списке
    unique_brands = Product.objects.values_list('brand_name', flat=True).distinct()
    filtered_products = all_products  # Инициализация переменной перед использованием

    # sort_params_instance = SortParams(request, all_products, unique_brands)
    #
    # filtered_products = sort_params_instance.gender_sort()
    # filtered_products = sort_params_instance.brand_sort()

    range_min_price = request.GET.get('min_price')
    range_max_price = request.GET.get('max_price')
    # print(type(range_min_price))
    # print(range_min_price)

    if range_min_price is not None and range_max_price is not None:
        range_min_price = int(range_min_price)
        range_max_price = int(range_max_price)
        # были ли изменения дефолтных значений из формы слайдера
        if range_min_price != 0 or range_max_price != 9000:
            filtered_products = Product.objects.filter(price__range=(range_min_price, range_max_price))

    # сортировка по брэнду
    sort_param = request.GET.get('brand_name', 'default')
    if sort_param in unique_brands:
        selected_brand = request.GET.get('brand_name', None)

        if selected_brand:
            filtered_products = all_products.filter(brand_name=selected_brand)

    # сортировка по гендеру
    selected_gender = request.GET.get('gender', None)
    if selected_gender:
        filtered_products = all_products.filter(gender=selected_gender)

    # сортировка по цене мин и макс
    sort_param = request.GET.get('sort', 'default')
    if sort_param == 'price_max':
        filtered_products = all_products.order_by('-price')
    elif sort_param == 'price_min':
        filtered_products = all_products.order_by('price')
    else:
        pass
    # Обработка значения 'default'

    # Применение пагинации
    paginator = Paginator(filtered_products, 6)  # Показываем кол-во товара на странице
    page = request.GET.get('page')

    try:
        filtered_products = paginator.page(page)
    except PageNotAnInteger:
        # Если page не является целым числом, отображаем первую страницу
        filtered_products = paginator.page(1)
    except EmptyPage:
        # Если страница выходит за пределы доступных страниц, отображаем последнюю страницу
        filtered_products = paginator.page(paginator.num_pages)

    return render(request, 'shop/index.html', {'categories': categories,
                                               # 'menu_data': menu_data,
                                               'products': filtered_products,
                                               'unique_brands': unique_brands,
                                               'sort_param': sort_param,
                                               'IMAGES_URL': IMAGES_URL})


def show_brand_catalog(request, brand_id):
    products = Product.objects.filter(brand_id=brand_id).prefetch_related('images')

    # запрос возвращает результат метода __str__
    brand = get_object_or_404(Brand, id=brand_id)
    # передача строки <title> в base.html через shop.context_processors.title
    title = f'Каталог бренда {brand}'
    # Получение текущего пути
    current_path = request.path_info
    # Генерация breadcrumbs
    breadcrumbs = generate_breadcrumbs(current_path, title)

    return render(request, 'shop/brand_catalog.html', {'products': products,
                                                       'IMAGES_URL': IMAGES_URL,
                                                       'breadcrumbs': breadcrumbs,
                                                       'title': title})


def product_detail(request, product_id):
    # Используем prefetch_related для получения связанных данных
    # to_attr - это аргумент, который используется в Prefetch для указания имени атрибута,
    # в который будут сохранены связанные объекты.
    # product_colors и product_sizes это произвольные имена для этих атрибутов.
    product = Product.objects.filter(id=product_id).prefetch_related(
        Prefetch('color', queryset=Color.objects.all(), to_attr='product_colors'),
        Prefetch('size', queryset=Size.objects.all(), to_attr='product_sizes'),
    ).first()

    # print(product.category_id)
    category_request = get_object_or_404(Category, id=product.category_id)
    # Получение текущей категории и ее потомков на основе последнего компонента пути
    parents_category = get_category_and_parents(category_request.slug)

    # print(parents_category)

    # Создание списка слагов из непустых компонентов пути
    slug_list = [x for x in parents_category if x]
    breadcrumbs = []
    for slug in slug_list:
        # Для каждого слага в списке строится запрос категории по слагу, и результат добавляется в "хлебные крошки"
        breadcrumbs.append(Category.objects.filter(slug=slug))

    print(breadcrumbs)

    # запрос возвращает результат метода __str__
    brand = get_object_or_404(Brand, id=product.brand_id)
    images = Product_Images.objects.filter(product=product)

    cart_product_form = CartAddProductForm()
    # Передаем данные в форму

templates/shop/base.html
<!DOCTYPE html>
<html lang="ru-RU">
{% load static %}
{#загрузка пользовательского фильтра из cart/templatetags/pluralize_ru.py#}
{% load pluralize_ru %}
{% load mptt_tags %}

<head>
<title>{{ title }}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href="{% static 'css/bootstrap.css' %}" rel='stylesheet' type='text/css' />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<!-- Custom Theme files -->
<link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/png">
<link href="{% static 'css/style.css' %}" rel='stylesheet' type='text/css' />
<link rel="stylesheet" href="{% static 'css/jquery.countdown.css' %}" />
<link rel="stylesheet" href="{% static 'css/flexslider.css' %}" type="text/css" media="screen" />
<!--webfont-->
<link href='http://fonts.googleapis.com/css?family=Raleway:100,200,300,400,500,600,700,800,900' rel='stylesheet' type='text/css'>
<!-- Подключение jQuery и jQuery UI -->
<script type="text/javascript" src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
{#<script src="https://code.jquery.com/jquery-3.7.1.min.js"></script>#}
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">


<!-- dropdown -->
<script src="{% static 'js/jquery.easydropdown.js' %}"></script>
<!-- start menu -->
<link href="{% static 'css/megamenu.css' %}" rel="stylesheet" type="text/css" media="all" />
<script type="text/javascript" src="{% static 'js/megamenu.js' %}"></script>
<script>$(document).ready(function(){$(".megamenu").megamenu();});</script>
<script src="{% static 'js/responsiveslides.min.js' %}"></script>
<script>
    $(function () {
      $("#slider").responsiveSlides({
      	auto: true,
      	nav: false,
      	speed: 500,
        namespace: "callbacks",
        pager: true,
      });
    });
</script>
<script src="{% static 'js/jquery.countdown.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>



</head>
<body>
<div class="header_top">
  <div class="container">
  	<div class="header_top-box">
     <div class="header-top-left">
		  <div class="clearfix"></div>
   			 </div>
			 <div class="cssmenu">
				<ul>
                    {% if user.is_authenticated %}
                    <li class="active"><a href="{% url 'orders:my_orders_list' %}">Мои заказы</a></li>
					<li class="active"><a href="{% url 'users:profile' %}">Личный профиль</a></li>
					<li><a href="{% url 'users:wishlist' %}">Избранное</a></li>
                    <li><a href="{% url 'users:logout' %}">Выйти из аккаунта</a></li>
                    {% else %}
					<li><a href="{% url 'users:login' %}">Войти</a></li>
					<li><a href="{% url 'users:register' %}">Регистрация</a></li>
                    {% endif %}
				</ul>
			</div>
			<div class="clearfix"></div>
   </div>
</div>
</div>
<div class="header_bottom">
	<div class="container">
	 <div class="header_bottom-box">
		<div class="header_bottom_left">
			<div class="logo">
				<a href="{% url 'shop:index' %}"><img src="{% static 'images/logo.png' %}" alt=""/></a>
			</div>
			<div class="clearfix"> </div>
		</div>
		<div class="header_bottom_right">
            <form action="{% url 'shop:product_search' %}" method="get">
                <div class="search">
                    <input type="text" name="search_query" value="Поиск товаров" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Поиск товаров';}">
                    <input type="submit" value="">
                </div>
            </form>
            <ul class="bag">
            <a href="{% url "cart:cart_detail" %}"><i class="bag_left"> </i></a>
                {% with total_items=cart|length %}
                    {% if total_items > 0 %}
                <a href="{% url "cart:cart_detail" %}"><li class="bag_right">
            <p>{{ total_items }} {{ total_items|pluralize_ru:"товар,товара,товаров" }}, {{ cart.get_total_price }}&nbsp;₽</p>
             </li></a>
                    {% else %}
             <a href="{% url "cart:cart_detail" %}"><li class="bag_right"><p>Корзина пуста</li></a>
                    {% endif %}
                {% endwith %}

	  			<div class="clearfix"> </div>
	  		</ul>
		</div>
		<div class="clearfix"> </div>
	</div>
</div>
</div>
<div class="menu">
	<div class="container">
		<div class="menu_box">
	    <ul class="megamenu skyblue">
			<li><a class="color2" href="{% url 'shop:index' %}">Главная</a></li>
            <li><a class="color3" href="#">Мужская одежда</a>
				<div class="megapanel">
					<div class="row">
						<div class="col1">
							<div class="h_nav">
                                <h4>Мужчинам</h4>
                            {% if descendants_category_1 %}
                                <ul>
                                {% recursetree descendants_category_1 %}
                                    <li>
                                        <a href="/category/{{ node.url_path }}/"><span
                                                class="price1">{{ node.name }}</span></a>

                                        {% if not node.is_leaf_node %}
{#                                            <ul style="padding-left: 20px">#}
                                            <ul>
                                                {{ children }}
                                            </ul>
                                        {% endif %}
                                    </li>
                                {% endrecursetree %}
                                </ul>
                            {% else %}
                                <p>Для горизонтального меню выводятся категории с id 1,2,3.
                                Которые создаются при запуске инсталлятора, перед началом заполнения</p>
                            {% endif %}


							</div>
						</div>

					  </div>
					</div>
			</li>
			<li><a class="color4" href="#">Женская одежда</a>
				<div class="megapanel">
					<div class="row">
						<div class="col1">
							<div class="h_nav">
								<h4>Женщинам</h4>
                                {% if descendants_category_2 %}
                                    <ul>
                                        {% recursetree descendants_category_2 %}
                                            <li>
                                                <a href="/category/{{ node.url_path }}/"><span
                                                        class="price1">{{ node.name }}</span></a>

                                                {% if not node.is_leaf_node %}
{#                                                     <ul style="padding-left: 20px">#}
                                                    <ul>
                                                        {{ children }}
                                                    </ul>
                                                {% endif %}
                                            </li>
                                        {% endrecursetree %}
                                    </ul>
                                {% else %}
                                    <p>Для горизонтального меню выводятся категории с id 1,2,3.
                                        Которые создаются при запуске инсталлятора, перед началом заполнения</p>
                                {% endif %}
							</div>
						</div>

					  </div>
					</div>
			</li>
            <li><a class="color10" href="404.html">Аксессуары</a></li>
			<li><a class="color8" href="{% url 'shop:contacts' %}">О магазине</a></li>
			<div class="clearfix"> </div>
		 </ul>
	  </div>
</div>
</div>

{% block content %}

{% endblock %}

<div class="footer">
	<div class="container">
		<img src="{% static 'images/pay.png' %}" class="img-responsive" alt=""/>
		<ul class="footer_nav">
		  <li><a href="{% url 'shop:index' %}">Главная</a></li>
{#		  <li><a href="#">Blog</a></li>#}
{#		  <li><a href="#">Shop</a></li>#}
{#		  <li><a href="#">Media</a></li>#}
{#		  <li><a href="#">Features</a></li>#}
{#		  <li><a href="#">About Us</a></li>#}
		  <li><a href="{% url 'shop:contacts' %}">О магазине</li>
		</ul>
{#		<p class="copy">Copyright&copy; 2015 Template by <a href="http://w3layouts.com" target="_blank"> w3layouts</a></p>#}
	</div>
</div>
</body>
</html>

templates/shop/category_path.html
{% extends 'shop/base.html' %}

{% block content %}
    <h1>Category Path</h1>
    
    <ul>
        {% for category in categories %}
            <li>{{ category.name }}</li>
        {% endfor %}
    </ul>
{% endblock %}

templates/shop/product_detail.html
{% extends 'shop/base.html' %}
{% block content %}
    {% load static %}
    {% load mptt_tags %}
{#    {% if path_list %}#}
{#        Путь:#}
{##}
{#        {% for path in path_list %}#}
{#            <a href="{% url 'shop:category_detail' path.slug %}">{{ path.name }}</a> |#}
{#        {% endfor %}#}
{##}
{#    {% endif %}#}

<!--content-->
    <div class="breadcrumb-box">
        <div class="container">
            <div class="menu_box">
                <ol class="breadcrumb">
                    <li>
                        <a href="{% url 'shop:index' %}">Главная</a>
                    </li>
                    {% for breadcrumb in breadcrumbs %}
                        {% for bcategory in breadcrumb %}
                            <li>
                                <a href="{% url 'shop:show_categories' url_path=bcategory.url_path %}">
                                    {{ bcategory.name }}</a>
                            </li>
                        {% endfor %}
                    {% endfor %}
                </ol>
            </div>
        </div>
    </div>

<div class="men">
    <div class="container">
        <div class="col-md-9">
            <div class="clearfix"></div>

    <div class="new-product">
    <div class="col-md-5 zoom-grid">
        <div class="flexslider">
            <ul class="slides">
                {% for image in images %}
                    <li data-thumb="{{ IMAGES_URL }}{{ image.img_big }}">
                        <div class="thumb-image">
                            <img src="{{ IMAGES_URL }}{{ image.img_big }}"
                                 alt="{{ product.name }} {{ product.brand }} data-imagezoom=" true"
                            class="img-responsive"">
                        </div>
                    </li>
                {% endfor %}

            </ul>
        </div>
    </div>
				<div class="col-md-7 dress-info">
					<div class="dress-name">
						<h3>{{ product.name }}</h3>
						<span>{{ product.price }}&nbsp;₽</span>
						<div class="clearfix"></div>
						<p class="m_text2">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo</p>

					</div>
					<div class="span span1">
						<p class="left">Брэнд</p>
						<p class="right"><a href="{% url 'shop:show_brand_catalog' brand.id %}">{{ brand.name }}</a></p>
						<div class="clearfix"></div>
					</div>
					<div class="span span2">
						<p class="left">Состав</p>
						<p class="right">{{ product.composition }}</p>
						<div class="clearfix"></div>
					</div>
                    <form action="{% url "cart:cart_add" product.id %}" method="post">
					<div class="span span1">
						<p class="left">Цвет</p>
						<p class="right">{{ cart_product_form.color }}</p>
						<div class="clearfix"></div>
					</div>
					<div class="span span2">
                        <p class="left">Размер</p>
						<p class="right">{{ cart_product_form.size }}</p>
						<div class="clearfix"></div>
					</div>
                    <div class="span span1">
                        <p class="left">Количество</p>
						<p class="right">{{ cart_product_form.quantity }}</p>
						<div class="clearfix"></div>
					</div>

                        {% csrf_token %}
                    <input type="submit" value="Добавить в корзину">
                    </form>

                <form id="wishlistForm" data-url="{% url 'users:wishlist' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="user_id" value="{{ user.id }}">
                <input type="hidden" name="product_id" value="{{ product.id }}">
                <button type="submit">Добавить в избранное</button>
                </form>


    <script src="{% static 'js/imagezoom.js' %}"></script>
    <!-- FlexSlider -->
    <script defer src="{% static 'js/jquery.flexslider.js' %}"></script>
    <script>
        // Can also be used with $(document).ready()
        $(window).load(function() {
          $('.flexslider').flexslider({
            animation: "slide",
            controlNav: "thumbnails"
          });
        });
    </script>

    <script>
        $(document).ready(function () {
            $("#wishlistForm").submit(function (event) {
                event.preventDefault();
                var form = $(this);
                var url = form.data("url");

                $.ajax({
                    type: "POST",
                    url: url,
                    data: form.serialize(),
                    headers: {
                        "X-Requested-With": "XMLHttpRequest"
                    },
                    success: function (data) {
                        // Обработка успешного выполнения запроса
                        if (data.status === "added") {
                            alert("Товар добавлен в избранное!");
                        } else if (data.status === "removed") {
                            alert("Товар удален из избранного.");
                        }
                    },
                    error: function (data) {
                        // Обработка ошибки
                        alert("Произошла ошибка при добавлении в избранное.");
                    }
                });
            });
        });
    </script>

                </div>
        <div class="clearfix"></div>

        <!---728x90--->
        <div class="reviews-tabs">
            <!-- Main component for a primary marketing message or call to action -->
            <ul class="nav nav-tabs responsive hidden-xs hidden-sm" id="myTab">
                <li class="test-class active"><a class="deco-none misc-class" href="#how-to">Дополнительное описание</a>
                </li>
                {#        <li class="test-class"><a href="#features">Specifications</a></li>#}

            </ul>

            <div class="tab-content responsive hidden-xs hidden-sm">
                <div class="tab-pane active" id="how-to">
                    <p class="tab-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nibh urna,
                        euismod ut ornare non, volutpat vel tortor. Integer laoreet placerat suscipit. Sed sodales
                        scelerisque commodo. Nam porta cursus lectus. Proin nunc erat, gravida a facilisis quis, ornare
                        id lectus. Proin consectetur nibh quis urna gravida mollis.This tab has icon in consectetur
                        adipiscing eliconse consectetur adipiscing elit. Vestibulum nibh urna, ctetur adipiscing elit.
                        Vestibulum nibh urna, t.consectetur adipiscing elit. Vestibulum nibh urna, Vestibulum nibh
                        urna,it.</p>
                    <p class="tab-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit,There are many
                        variations of passages of Lorem Ipsum available,
                        sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                </div>
                <div class="tab-pane" id="features">
                    <p class="tab-text">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum nibh urna,
                        euismod ut ornare non, volutpat vel tortor. Integer laoreet placerat suscipit. Sed sodales
                        scelerisque commodo. Nam porta cursus lectus. Proin nunc erat, gravida a facilisis quis, ornare
                        id lectus. Proin consectetur nibh quis urna gravida mollis.This tab has icon in consectetur
                        adipiscing eliconse consectetur adipiscing elit. Vestibulum nibh urna, ctetur adipiscing elit.
                        Vestibulum nibh urna, t.consectetur adipiscing elit. Vestibulum nibh urna, Vestibulum nibh
                        urna,it.</p>
                    <p class="tab-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit,There are many
                        variations of passages of Lorem Ipsum available,
                        sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                </div>

            </div>
        </div>
    </div>

        </div>

        <div class="clearfix"></div>
    </div>
    </div>

{##}
{##}
{#    <h1>{{ product.name }}</h1>#}
{#    <h3><a href="{% url 'shop:show_brand_catalog' brand.id %}">{{ brand.name }}</a></h3>#}
{#    <h3>{{ product.description }}</h3>#}
{#    <h3>Цена: {{ product.price }}</h3>#}
{#    <!-- Другие данные о продукте -->#}
{#    <h2>Изображения продукта</h2>#}
{#    <ul>#}
{#        <ul>#}
{#    {% for image in images %}#}
{#        <li>#}
{#            <img src="{% if forloop.first %}{{ IMAGES_URL }}{{ image.img_small }}{% else %}{{ IMAGES_URL }}{{ image.img_thumb }}{% endif %}" alt="{{ product.name }} {{ product.brand }}">#}
{#        </li>#}
{#    {% endfor %}#}
{#</ul>#}


{% endblock %}

templates/shop/search.html
{% extends "shop/base.html" %}

{% block content %}
    {% load pluralize_result %}

<div class="men">
	<div class="container">
	    <div class="wishlist">
    {% if search_query %}
        <strong>По вашему запросу: "{{ search_query }}"</strong><br>
        <strong>
            {% with results.count as total_results %}
                Найдено {{ total_results }} {{ total_results|pluralize_result:"результат,результата,результатов" }}
            {% endwith %}
        </strong><br><br>
        <ul>
            {% for product in results %}
                <li>
                    <a href="{% url 'shop:product_detail' product.id %}">{{ product.name }} {{ product.brand_name }}</a>
                </li>
            {% empty %}
                <p>По вашему запросу "{{ search_query }}" ничего не найдено</p>
            {% endfor %}
        </ul>
        <br>
        <p><a href="{% url "shop:product_search" %}">Искать снова</a></p>
    {% else %}
        <h1>Поиск товаров:</h1>
        <form method="get">
            {{ form.search_query }}
            <input type="submit" value="Search">
        </form>
    {% endif %}
        </div>
	</div>
</div>


{% endblock %}